apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Values.cluster }}-helm-guestbook'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    name: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
